fix: crash from wrong canOutputAll method descriptor
The canOutputAll(ItemStack[], FluidStack[]) Mixin descriptor was
missing the array bracket: 'Lnet/minecraft/item/ItemStack;' instead
of '[Lnet/minecraft/item/ItemStack;'. This caused the Mixin annotation
processor to fail to find the method, which broke class transformation
of MTEMultiBlockBase, cascading to a NoClassDefFoundError for
MTEExtendedPowerMultiBlockBase during GT's preInit.

Fixed all 3 canOutputAll descriptors to use correct array notation.